language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode9.4

    - os: osx
      osx_image: xcode10.3

cache:
  directories:
    - /usr/local/Cellar/cryptopp
    - $HOME/Library/Caches/Homebrew

before_cache:
  - brew cleanup && rm -rf $HOME/Library/Caches/Homebrew/dcore--git

before_install:
  - brew tap nlohmann/json
  - test -L /usr/local/opt/cryptopp || test ! -d /usr/local/Cellar/cryptopp || brew link cryptopp || true;
  - test ! -L /usr/local/opt/cryptopp || brew upgrade cryptopp || true;
  - TAPS_DIR=$(brew --prefix)/Homebrew/Library/Taps
  - mkdir $TAPS_DIR/decentfoundation
  - ln -s $TRAVIS_BUILD_DIR $TAPS_DIR/decentfoundation/homebrew-dcore

script:
  # ignore 'Dependency nlohmann/json/nlohmann_json should not use option with-cmake'
  - brew audit --except-cops=FormulaAudit/Miscellaneous dcore
  - if [ -z "$TRAVIS_TAG" ]; then DCORE_HEAD="--HEAD"; fi
  - brew install $DCORE_HEAD --build-bottle --verbose dcore
  - brew bottle --root-url=https://dl.bintray.com/decentfoundation/homebrew --skip-relocation --no-rebuild dcore
  - DCORE_VERSION=$(brew list --versions dcore | sed 's/.* //')
  - sed "s/VERSION/$DCORE_VERSION/" .bintray.json > descriptor.json

deploy:
  skip_cleanup: true
  provider: bintray
  file: descriptor.json
  user: decent-dcore
  key:
    secure: jb9evXlMVAi1H5ILVUvSdxCBCeU9Q6oMD/+Pm9BuuXdV/SJrqg/tWLvHf4JqwI3ZvtqACm+qTq1BEt5jspnbXtmIDKKQBZdyELtRmlkXBcGa3sL4HzXmCcbGn/VAX+i1IvvIDuG+F40vBWf3OvAQEUCjzA+w3SEezQqMit+QDIhoDH15MdS6m0FHTJaeFLDgA8R8gqhf/KJSA9CfhdthGCHDfz22hQ1jw1gro987ePGSkh7YRmQszCoeAqqSbBy5Xm4zbT4YMezL6yw1MyzMOoRZmmt6wDO/C1l6VtYZfIm45P7WsMe1LLjldiSL7xNgzp2WP+0HhKAgMSrnbPUEMVLejjrpAsJCBivrTYGr8NRP7cWbmo6iirg30UubfXlAaurLe4NqHfdeWiUgX4fb1IU75tVvWtPr+P0TNNA6uORIfXV9g4oVHu66bOC90/3nr+sVMPwcyQCpBaahewGwwXWKerpW/fFWcnNOBO2qW3c7kecIV5Zjb942OyK5qjrdwtuMoYClxnGyW0T1jWsn5GDxxS8xcAn/hZvm15lePShJb4XHDfuC0RfuDfIP6tvSMpqE+RLj0AFf8gYGYHTtB/kn2P82d+nl9+k4VzmY/GNp7TWcce9v7jSEOThfGdd044MzPjhMNQXTKTChye1YRVyx+DfshfYbUmkp+q75s+Y=
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
